apiVersion: apps/v1
kind: Deployment
metadata:
  name: leoiuei
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leoiuei
  template:
    metadata:
      labels:
        app: leoiuei
    spec:
      containers:
      - image: okteto.dev/leoiuei:latest
        name: leoiuei
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2898d7f8-2e13-4113-abb6-8aedfb791082"
        - name: Vless_Path
          value: "/vlgsfe555"
        - name: Vmess_UUID
          value: "2898d7f8-2e13-4113-abb6-8aedfb791082"
        - name: Vmess_Path
          value: "/vmgert4666"
        - name: Share_Path
          value: "/v2link"
